import { derived, type Readable } from 'svelte/store';
import type { Edits, ElementEdits } from '$lib/modules/connection';
import { edits, elementEdits } from '$lib/modules/connection';

const DOWNLOAD_FILENAME = 'neomorph-theme.css';

function declarations(map: Record<string, string>): string {
  return Object.entries(map)
    .map(([name, value]) => `\t${name}: ${value};`)
    .join('\n');
}

/** Token overrides → `:root { … }` blocks (one per scraped host). */
function tokenBlocks(value: Edits): string[] {
  const blocks: string[] = [];
  for (const [host, vars] of Object.entries(value)) {
    if (Object.keys(vars).length === 0) {
      continue;
    }
    // The document host maps to :root; other hosts are shadow roots → :host.
    if (host === 'document') {
      blocks.push(`:root {\n${declarations(vars)}\n}`);
    } else {
      blocks.push(`/* host: ${host} */\n:host {\n${declarations(vars)}\n}`);
    }
  }
  return blocks;
}

/** Per-element overrides → `selector { … }` blocks. */
function elementBlocks(value: ElementEdits): string[] {
  const blocks: string[] = [];
  for (const [selector, decls] of Object.entries(value)) {
    if (Object.keys(decls).length === 0) {
      continue;
    }
    blocks.push(`${selector} {\n${declarations(decls)}\n}`);
  }
  return blocks;
}

function buildCss(tokenEdits: Edits, perElement: ElementEdits): string {
  const tokens = tokenBlocks(tokenEdits);
  const elements = elementBlocks(perElement);
  if (tokens.length === 0 && elements.length === 0) {
    return '';
  }
  const parts: string[] = ['/* Generated by Neomorph Studio */'];
  if (tokens.length > 0) {
    parts.push(`/* Theme tokens */\n${tokens.join('\n\n')}`);
  }
  if (elements.length > 0) {
    parts.push(`/* Element overrides (best-effort selectors) */\n${elements.join('\n\n')}`);
  }
  return `${parts.join('\n\n')}\n`;
}

export const generatedCss: Readable<string> = derived(
  [edits, elementEdits],
  ([$edits, $elementEdits]) => buildCss($edits, $elementEdits)
);

export const hasOutput: Readable<boolean> = derived(generatedCss, (css) => css.length > 0);

export const outputStats: Readable<{ tokens: number; elements: number }> = derived(
  [edits, elementEdits],
  ([$edits, $elementEdits]) => {
    let tokens = 0;
    for (const vars of Object.values($edits)) {
      tokens += Object.keys(vars).length;
    }
    return { tokens, elements: Object.keys($elementEdits).length };
  }
);

function escapeHtml(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/**
 * Lightweight CSS syntax highlighting → HTML. The input is HTML-escaped first,
 * so the returned string is safe to render with {@html}. Colours are applied by
 * the `.cm-*` classes defined in theme/components.css.
 */
export function highlightCss(css: string): string {
  return escapeHtml(css)
    .replace(/\/\*[\s\S]*?\*\//g, (match) => `<span class="cm-comment">${match}</span>`)
    .replace(
      /^(\t*)([\w-]+)(\s*:\s*)([^;]+)(;)/gm,
      (_match, indent, prop, colon, value, semi) =>
        `${indent}<span class="cm-prop">${prop}</span>${colon}<span class="cm-value">${value}</span>${semi}`
    )
    .replace(
      /^([^\n{}<]+?)(\s*\{)$/gm,
      (_match, selector, brace) => `<span class="cm-selector">${selector}</span>${brace}`
    );
}

export async function copyCss(css: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(css);
    return true;
  } catch {
    return false;
  }
}

export function downloadCss(css: string): void {
  const blob = new Blob([css], { type: 'text/css' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = DOWNLOAD_FILENAME;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}
